### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by sffr-dev** [nikita-shpikin/MyFirstLayout#1]
1. Убираем все `position: absolute`. Он не нужны
2. Для всех h1-5 задайте `font-weight: normal;`
3. https://github.com/nikita-shpikin/MyFirstLayout/blob/eec31610f375982daa4a08ab9b250d52ae13e3e4/index.html#L88 Лучше сделать кнопки или просто `div`. Следующим заданием будет создание слейдера, с радио-кнопками не удобно работать
4. Все иконки сделать так же, как `control-image`. При этом задать им один и тот же класс.
5. https://github.com/nikita-shpikin/MyFirstLayout/blob/eec31610f375982daa4a08ab9b250d52ae13e3e4/index.html#L276 Текст должен быть текстом.
6. На 1024 верстка разваливается. На 768 очень большие отступы. Либо всю мобильную верстку оберните в `(max-width: 1200px)`, либо более тщательно сделайте версию для планшетов. При этом `(max-width: 376px)` нужно заменить на `(max-width: 768px)`

**Comment by nikita-shpikin** [comment]
Всё исправил :1st_place_medal:
