### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by sffr-dev** [nikita-shpikin/MyFirstLayout#2]
1. https://github.com/nikita-shpikin/MyFirstLayout/blob/23179284422f67c9926db805317bbb127bd452d6/index.html#L330 Зачем эта обертка? По-моему она лишняя и мешает нормальному расположению элементов
2. https://github.com/nikita-shpikin/MyFirstLayout/blob/23179284422f67c9926db805317bbb127bd452d6/index.html#L325 Секция наезжает на верхний блок на мобилке
3. https://github.com/nikita-shpikin/MyFirstLayout/blob/23179284422f67c9926db805317bbb127bd452d6/index.html#L158 У этих блоков лучше убрать фиксированную высоту и задать фоновой картинке расположение в левом углу без повтора
4. От радио-кнопок так и не избавились

**Comment by nikita-shpikin** [comment]
1. В ней два лейбла под свойством флекс 
Остальное всё исправил
